In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
print(a[0])

1


In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
np.ones(5), np.zeros(5), a.reshape((5,1))

(array([1., 1., 1., 1., 1.]),
 array([0., 0., 0., 0., 0.]),
 array([[1],
        [2],
        [3],
        [4],
        [5]]))

In [6]:
a.T

array([1, 2, 3, 4, 5])

In [7]:
a.size

5

In [8]:
a.shape

(5,)

In [9]:
a.sum()

np.int64(15)

In [10]:
a.min(), a.mean(), a.max()

(np.int64(1), np.float64(3.0), np.int64(5))

In [35]:
np.random.randint(1,5,size=(2,5))

array([[3, 3, 1, 2, 2],
       [3, 1, 2, 2, 4]], dtype=int32)

In [42]:
np.random.rand(10).reshape((2,5))

array([[0.81263298, 0.65447173, 0.60227782, 0.85020852, 0.23821885],
       [0.86337113, 0.28517581, 0.08316808, 0.3678991 , 0.14378014]])

In [31]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
np.arange(1,11).reshape((2,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [61]:
np.arange(1,11).reshape((2,5)).T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [62]:
a.ndim

1

In [63]:
a.dtype

dtype('int64')

In [64]:
np.sqrt(a), np.exp(a), np.log(a)

(array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798]),
 array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
        148.4131591 ]),
 array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791]))

In [65]:
b=np.random.randint(5,11,size=(4,5))
b

array([[10,  5,  8,  5,  9],
       [ 5,  7,  8,  5, 10],
       [ 9, 10,  7,  7,  5],
       [ 8,  7,  8,  9, 10]], dtype=int32)

In [66]:
b[:2]

array([[10,  5,  8,  5,  9],
       [ 5,  7,  8,  5, 10]], dtype=int32)

In [67]:
b[2:,:3]

array([[ 9, 10,  7],
       [ 8,  7,  8]], dtype=int32)

# Normalised Data

## mean=0, standard deviation is 1

In [75]:
((b-b.mean())/b.std())

array([[ 1.33333333, -1.44444444,  0.22222222, -1.44444444,  0.77777778],
       [-1.44444444, -0.33333333,  0.22222222, -1.44444444,  1.33333333],
       [ 0.77777778,  1.33333333, -0.33333333, -0.33333333, -1.44444444],
       [ 0.22222222, -0.33333333,  0.22222222,  0.77777778,  1.33333333]])

In [76]:
b[b>b.mean()]

array([10,  8,  9,  8, 10,  9, 10,  8,  8,  9, 10], dtype=int32)

In [82]:
a=np.random.randint(10,size=(1,5)) 
b=np.random.randint(10,size=(5))
print(a,b)
print(a.ndim,b.ndim)

[[6 7 5 0 5]] [9 3 4 8 8]
2 1


In [81]:
np.array([[0,5,1,5,2]]) == np.array([0,5,1,5,2])

array([[ True,  True,  True,  True,  True]])