In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from sklearn.model_selection import train_test_split
import nltk

In [2]:
with open('hamlet.txt','r') as file:
    text=file.read().lower()
text

"[the tragedie of hamlet by william shakespeare 1599]\n\n\nactus primus. scoena prima.\n\nenter barnardo and francisco two centinels.\n\n  barnardo. who's there?\n  fran. nay answer me: stand & vnfold\nyour selfe\n\n   bar. long liue the king\n\n   fran. barnardo?\n  bar. he\n\n   fran. you come most carefully vpon your houre\n\n   bar. 'tis now strook twelue, get thee to bed francisco\n\n   fran. for this releefe much thankes: 'tis bitter cold,\nand i am sicke at heart\n\n   barn. haue you had quiet guard?\n  fran. not a mouse stirring\n\n   barn. well, goodnight. if you do meet horatio and\nmarcellus, the riuals of my watch, bid them make hast.\nenter horatio and marcellus.\n\n  fran. i thinke i heare them. stand: who's there?\n  hor. friends to this ground\n\n   mar. and leige-men to the dane\n\n   fran. giue you good night\n\n   mar. o farwel honest soldier, who hath relieu'd you?\n  fra. barnardo ha's my place: giue you goodnight.\n\nexit fran.\n\n  mar. holla barnardo\n\n   bar. 

In [3]:
t=Tokenizer()
t.fit_on_texts([text])
print(len(t.word_index))
t.word_index

4817


{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'you': 6,
 'a': 7,
 'my': 8,
 'it': 9,
 'in': 10,
 'that': 11,
 'ham': 12,
 'is': 13,
 'not': 14,
 'his': 15,
 'this': 16,
 'with': 17,
 'your': 18,
 'but': 19,
 'for': 20,
 'me': 21,
 'lord': 22,
 'as': 23,
 'what': 24,
 'he': 25,
 'be': 26,
 'so': 27,
 'him': 28,
 'haue': 29,
 'king': 30,
 'will': 31,
 'no': 32,
 'our': 33,
 'we': 34,
 'on': 35,
 'are': 36,
 'if': 37,
 'all': 38,
 'then': 39,
 'shall': 40,
 'by': 41,
 'thou': 42,
 'come': 43,
 'or': 44,
 'hamlet': 45,
 'good': 46,
 'do': 47,
 'hor': 48,
 'her': 49,
 'let': 50,
 'now': 51,
 'thy': 52,
 'how': 53,
 'more': 54,
 'they': 55,
 'from': 56,
 'enter': 57,
 'at': 58,
 'was': 59,
 'oh': 60,
 'like': 61,
 'most': 62,
 'there': 63,
 'well': 64,
 'know': 65,
 'selfe': 66,
 'would': 67,
 'them': 68,
 'loue': 69,
 'may': 70,
 "'tis": 71,
 'vs': 72,
 'sir': 73,
 'qu': 74,
 'which': 75,
 'did': 76,
 'why': 77,
 'laer': 78,
 'giue': 79,
 'thee': 80,
 'ile': 81,
 'must': 82,
 'hath': 

In [4]:
with open('hamlet.txt','r') as file:
    text_lines=file.readlines()
for i in text_lines:
    if i=='\n':
        text_lines.remove('\n')
text_lines

['[The Tragedie of Hamlet by William Shakespeare 1599]\n',
 'Actus Primus. Scoena Prima.\n',
 'Enter Barnardo and Francisco two Centinels.\n',
 "  Barnardo. Who's there?\n",
 '  Fran. Nay answer me: Stand & vnfold\n',
 'your selfe\n',
 '   Bar. Long liue the King\n',
 '   Fran. Barnardo?\n',
 '  Bar. He\n',
 '   Fran. You come most carefully vpon your houre\n',
 "   Bar. 'Tis now strook twelue, get thee to bed Francisco\n",
 "   Fran. For this releefe much thankes: 'Tis bitter cold,\n",
 'And I am sicke at heart\n',
 '   Barn. Haue you had quiet Guard?\n',
 '  Fran. Not a Mouse stirring\n',
 '   Barn. Well, goodnight. If you do meet Horatio and\n',
 'Marcellus, the Riuals of my Watch, bid them make hast.\n',
 'Enter Horatio and Marcellus.\n',
 "  Fran. I thinke I heare them. Stand: who's there?\n",
 '  Hor. Friends to this ground\n',
 '   Mar. And Leige-men to the Dane\n',
 '   Fran. Giue you good night\n',
 "   Mar. O farwel honest Soldier, who hath relieu'd you?\n",
 "  Fra. Barnardo

In [5]:
import re
for i in range(len(text_lines)):
    text_lines[i]=re.sub("(^\s*)|(\n)",'',text_lines[i]).lower()
text_lines_copy=text_lines
text_lines

['[the tragedie of hamlet by william shakespeare 1599]',
 'actus primus. scoena prima.',
 'enter barnardo and francisco two centinels.',
 "barnardo. who's there?",
 'fran. nay answer me: stand & vnfold',
 'your selfe',
 'bar. long liue the king',
 'fran. barnardo?',
 'bar. he',
 'fran. you come most carefully vpon your houre',
 "bar. 'tis now strook twelue, get thee to bed francisco",
 "fran. for this releefe much thankes: 'tis bitter cold,",
 'and i am sicke at heart',
 'barn. haue you had quiet guard?',
 'fran. not a mouse stirring',
 'barn. well, goodnight. if you do meet horatio and',
 'marcellus, the riuals of my watch, bid them make hast.',
 'enter horatio and marcellus.',
 "fran. i thinke i heare them. stand: who's there?",
 'hor. friends to this ground',
 'mar. and leige-men to the dane',
 'fran. giue you good night',
 "mar. o farwel honest soldier, who hath relieu'd you?",
 "fra. barnardo ha's my place: giue you goodnight.",
 'exit fran.',
 'mar. holla barnardo',
 'bar. say, w

In [6]:
[text_lines[0]],t.texts_to_sequences([text_lines[0]])

(['[the tragedie of hamlet by william shakespeare 1599]'],
 [[1, 687, 4, 45, 41, 1886, 1887, 1888]])

In [7]:
possibilities=[]
for i in range(len(text_lines)):
    token=t.texts_to_sequences([text_lines[i]])[0]
    for i in range(2,len(token)):
        possibilities.append(token[:i])
possibilities

[[1, 687],
 [1, 687, 4],
 [1, 687, 4, 45],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1180, 1889],
 [1180, 1889, 1890],
 [57, 407],
 [57, 407, 2],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181, 177],
 [407, 1182],
 [408, 162],
 [408, 162, 377],
 [408, 162, 377, 21],
 [408, 162, 377, 21, 247],
 [451, 224],
 [451, 224, 248],
 [451, 224, 248, 1],
 [408, 6],
 [408, 6, 43],
 [408, 6, 43, 62],
 [408, 6, 43, 62, 1893],
 [408, 6, 43, 62, 1893, 96],
 [408, 6, 43, 62, 1893, 96, 18],
 [451, 71],
 [451, 71, 51],
 [451, 71, 51, 1894],
 [451, 71, 51, 1894, 567],
 [451, 71, 51, 1894, 567, 378],
 [451, 71, 51, 1894, 567, 378, 80],
 [451, 71, 51, 1894, 567, 378, 80, 3],
 [451, 71, 51, 1894, 567, 378, 80, 3, 273],
 [408, 20],
 [408, 20, 16],
 [408, 20, 16, 1895],
 [408, 20, 16, 1895, 114],
 [408, 20, 16, 1895, 114, 379],
 [408, 20, 16, 1895, 114, 379, 71],
 [408, 20, 16, 1895, 114, 379, 71, 883],
 [2, 5],
 [2, 5, 92],
 [2, 5, 92, 688],
 [2, 5, 92, 688, 58],
 [346, 29

In [8]:
max_length=0
for i in possibilities:
    max_length=max(max_length,len(i))
max_length

13

In [9]:
for i in range(len(possibilities)):
    possibilities[i]=pad_sequences([possibilities[i]],padding='pre',maxlen=max_length)[0]
possibilities

[array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1, 687],
       dtype=int32),
 array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1, 687,   4],
       dtype=int32),
 array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   1, 687,   4,  45],
       dtype=int32),
 array([  0,   0,   0,   0,   0,   0,   0,   0,   1, 687,   4,  45,  41],
       dtype=int32),
 array([   0,    0,    0,    0,    0,    0,    0,    1,  687,    4,   45,
          41, 1886], dtype=int32),
 array([   0,    0,    0,    0,    0,    0,    1,  687,    4,   45,   41,
        1886, 1887], dtype=int32),
 array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        1180, 1889], dtype=int32),
 array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1180,
        1889, 1890], dtype=int32),
 array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  57, 407],
       dtype=int32),
 array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  57, 407,   2],
       dtype=in

In [10]:
possibilities=np.array(possibilities)
possibilities

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,  687,    4,   45],
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4]], dtype=int32)

In [11]:
x=possibilities[:,:-1]
y=possibilities[:,-1]

In [12]:
x

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       ...,
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       [   0,    0,    0, ...,    4,   45, 1047]], dtype=int32)

In [13]:
y

array([ 687,    4,   45, ...,   45, 1047,    4], dtype=int32)

In [14]:
x.shape,y.shape

((21850, 12), (21850,))

In [15]:
y=tf.keras.utils.to_categorical(y,num_classes=len(t.word_index))
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [16]:
y.shape

(21850, 4817)

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.15,random_state=19)

In [18]:
x_train.shape

(18572, 12)

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense, Dropout

In [20]:
model=Sequential()
model.add(Embedding(len(t.word_index)+1,100,input_shape=(12,)))
model.add(GRU(120, return_sequences=True))
model.add(Dropout(0.2))
model.add(GRU(80))
model.add(Dropout(0.1))
model.add(Dense(len(t.word_index),activation="softmax"))
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])
model.summary()


d:\ML\11\env\lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 12, 100)        │       481,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ (None, 12, 120)        │        79,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 12, 120)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_1 (GRU)                     │ (None, 80)             │        48,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 80)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 4817)           │       390,177 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,000,377 (3.82 MB)

 Trainable params: 1,000,377 (3.82 MB)

 Non-trainable params: 0 (0.00 B)

In [21]:
from tensorflow.keras.callbacks import EarlyStopping
#es=EarlyStopping(monitor='val_loss',patience=15,restore_best_weights=True)
model.fit(x_train,y_train,epochs=100,validation_data=(x_test,y_test),verbose=1)

Epoch 1/100
581/581 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - accuracy: 0.0332 - loss: 7.0059 - val_accuracy: 0.0451 - val_loss: 6.4799
Epoch 2/100
581/581 ━━━━━━━━━━━━━━━━━━━━ 9s 15ms/step - accuracy: 0.0458 - loss: 6.2286 - val_accuracy: 0.0494 - val_loss: 6.5464
Epoch 3/100
581/581 ━━━━━━━━━━━━━━━━━━━━ 9s 15ms/step - accuracy: 0.0624 - loss: 5.9596 - val_accuracy: 0.0595 - val_loss: 6.5238
Epoch 4/100
581/581 ━━━━━━━━━━━━━━━━━━━━ 9s 15ms/step - accuracy: 0.0799 - loss: 5.6635 - val_accuracy: 0.0677 - val_loss: 6.5242
Epoch 5/100
581/581 ━━━━━━━━━━━━━━━━━━━━ 9s 15ms/step - accuracy: 0.0977 - loss: 5.3923 - val_accuracy: 0.0677 - val_loss: 6.6011
Epoch 6/100
581/581 ━━━━━━━━━━━━━━━━━━━━ 9s 15ms/step - accuracy: 0.1104 - loss: 5.1725 - val_accuracy: 0.0665 - val_loss: 6.7218
Epoch 7/100
581/581 ━━━━━━━━━━━━━━━━━━━━ 9s 15ms/step - accuracy: 0.1201 - loss: 4.9454 - val_accuracy: 0.0659 - val_loss: 6.8178
Epoch 8/100
581/581 ━━━━━━━━━━━━━━━━━━━━ 9s 15ms/step - accuracy: 0.1311 - loss: 4.7645 -

In [22]:
x_test[0],x_train[0]

(array([   0,    0,    0,    0,    0,    0,    0,   34,   36, 1408, 3225,
          38], dtype=int32),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  0, 19, 23, 34], dtype=int32))

In [23]:
pred=np.argmax(model.predict(np.array([[0,0,0,0,0,0,0,0,0,0,34,36]])),axis=1)
for word, index in t.word_index.items():
    if index == pred:
        print(word)
        break

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 440ms/step
arrant


In [24]:
sentence="Together with that".lower()
sentence=t.texts_to_sequences([sentence])[0]
sentence=pad_sequences([sentence],padding='pre',maxlen=max_length-1)[0]
pred=np.argmax(model.predict(np.array([sentence])),axis=1)
for word, index in t.word_index.items():
    if index == pred:
        print(word)
        break

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 416ms/step
faire


In [25]:
sentence="i will speake".lower()
sentence=t.texts_to_sequences([sentence])[0]
sentence=pad_sequences([sentence],padding='pre',maxlen=max_length-1)[0]
pred=np.argmax(model.predict(np.array([sentence])),axis=1)
for word, index in t.word_index.items():
    if index == pred:
        print(word)
        break

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
daggers


In [27]:
sentence="loose not thy".lower()
sentence=t.texts_to_sequences([sentence])[0]
sentence=pad_sequences([sentence],padding='pre',maxlen=max_length-1)[0]
pred=np.argmax(model.predict(np.array([sentence])),axis=1)
for word, index in t.word_index.items():
    if index == pred:
        print(word)
        break

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
nature


In [26]:
t.word_index.items()

dict_items([('the', 1), ('and', 2), ('to', 3), ('of', 4), ('i', 5), ('you', 6), ('a', 7), ('my', 8), ('it', 9), ('in', 10), ('that', 11), ('ham', 12), ('is', 13), ('not', 14), ('his', 15), ('this', 16), ('with', 17), ('your', 18), ('but', 19), ('for', 20), ('me', 21), ('lord', 22), ('as', 23), ('what', 24), ('he', 25), ('be', 26), ('so', 27), ('him', 28), ('haue', 29), ('king', 30), ('will', 31), ('no', 32), ('our', 33), ('we', 34), ('on', 35), ('are', 36), ('if', 37), ('all', 38), ('then', 39), ('shall', 40), ('by', 41), ('thou', 42), ('come', 43), ('or', 44), ('hamlet', 45), ('good', 46), ('do', 47), ('hor', 48), ('her', 49), ('let', 50), ('now', 51), ('thy', 52), ('how', 53), ('more', 54), ('they', 55), ('from', 56), ('enter', 57), ('at', 58), ('was', 59), ('oh', 60), ('like', 61), ('most', 62), ('there', 63), ('well', 64), ('know', 65), ('selfe', 66), ('would', 67), ('them', 68), ('loue', 69), ('may', 70), ("'tis", 71), ('vs', 72), ('sir', 73), ('qu', 74), ('which', 75), ('did', 76